### ISSUE TITLE
Resolve Alias 

### ISSUE THREAD

**Issue by kishorevarma** [glenjamin/ultimate-hot-reloading-example#2]
Hey,

I have added new alias in your example and tried, but it didn't worked. following is the code,

--- webpack.config.js
I have added two test folders(test, tes1)  inside the components folder, and moved App.js into test1 folder  

```
  resolve: {
    extensions: ['', '.js'],
    alias: {
      request: 'browser-request',
      components: path.join(__dirname, 'client/components/test/test1') 
    }
  }
```

--- server-render.js
In this file instead of giving relative path('./components/test/test1/App'), I gave 'components/App' and expected components will be replaced by alias.

```
var App = require('components/App');
```

Could you let me know if I am doing anything wrong?  following is the error

```
Cannot find module 'components/App'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (/home/kishore/code/ultimate-hot-reloading-example/client/server-render.js:5:11)
   at Module._compile (module.js:460:26)
   at normalLoader (/home/kishore/code/ultimate-hot-reloading-example/node_modules/babel-core/lib/api/register/node.js:199:5)
   at Object.require.extensions.(anonymous function) [as .js] (/home/kishore/code/ultimate-hot-reloading-example/node_modules/babel-core/lib/api/register/node.js:216:7)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
```

**Comment by glenjamin** [comment]
alias is a core webpack feature, it only kicks if there's an exact match.

You can achieve what you describe via one of the context modification plugins - http://webpack.github.io/docs/list-of-plugins.html#config

However, I'd suggest that using relative file paths in standard CommonJS style is preferrable.

**Comment by kishorevarma** [comment]
Thanks glenjamin, actually it works if you use the alias in client side,but not in the server side.
--- components/index.js 
following code will work

```
var App = require('components/App');
```

**Comment by glenjamin** [comment]
Oh? I stand corrected!

The server side in this demo doesn't use webpack - so any webpack settings only kick in on the client.

If you want aliases on the server you'd need to use a second bundle and require() it into the node app.
